
CREATE TABLE [dbo].[iller](
    [id] [int] IDENTITY(1,1) NOT NULL,
    [sehir] [nvarchar](255) NULL,
 CONSTRAINT [PK_iller] PRIMARY KEY CLUSTERED 
(
    [id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[iller] ON
INSERT [dbo].[iller] ([id], [sehir]) VALUES (1, N'ADANA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (2, N'ADIYAMAN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (3, N'AFYON')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (4, N'AÐRI')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (5, N'AMASYA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (6, N'ANKARA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (7, N'ANTALYA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (8, N'ARTVÝN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (9, N'AYDIN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (10, N'BALIKESÝR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (11, N'BÝLECÝK')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (12, N'BÝNGÖL')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (13, N'BÝTLÝS')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (14, N'BOLU')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (15, N'BURDUR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (16, N'BURSA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (17, N'ÇANAKKALE')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (18, N'ÇANKIRI')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (19, N'ÇORUM')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (20, N'DENÝZLÝ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (21, N'DÝYARBAKIR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (22, N'EDÝRNE')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (23, N'ELAZIÐ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (24, N'ERZÝNCAN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (25, N'ERZURUM')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (26, N'ESKÝÞEHÝR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (27, N'GAZÝANTEP')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (28, N'GÝRESUN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (29, N'GÜMÜÞHANE')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (30, N'HAKKARÝ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (31, N'HATAY')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (32, N'ISPARTA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (33, N'ÝÇEL')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (34, N'ÝSTANBUL')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (35, N'ÝZMÝR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (36, N'KARS')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (37, N'KASTAMONU')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (38, N'KAYSERÝ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (39, N'KIRKLARELÝ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (40, N'KIRÞEHÝR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (41, N'KOCAELÝ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (42, N'KONYA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (43, N'KÜTAHYA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (44, N'MALATYA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (45, N'MANÝSA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (46, N'KAHRAMANMARAÞ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (47, N'MARDÝN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (48, N'MUÐLA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (49, N'MUÞ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (50, N'NEVÞEHÝR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (51, N'NÝÐDE')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (52, N'ORDU')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (53, N'RÝZE')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (54, N'SAKARYA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (55, N'SAMSUN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (56, N'SÝÝRT')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (57, N'SÝNOP')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (58, N'SÝVAS')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (59, N'TEKÝRDAÐ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (60, N'TOKAT')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (61, N'TRABZON')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (62, N'TUNCELÝ')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (63, N'ÞANLIURFA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (64, N'UÞAK')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (65, N'VAN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (66, N'YOZGAT')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (67, N'ZONGULDAK')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (68, N'AKSARAY')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (69, N'BAYBURT')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (70, N'KARAMAN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (71, N'KIRIKKALE')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (72, N'BATMAN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (73, N'ÞIRNAK')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (74, N'BARTIN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (75, N'ARDAHAN')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (76, N'IÐDIR')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (77, N'YALOVA')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (78, N'KARABÜK')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (79, N'KÝLÝS')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (80, N'OSMANÝYE')
INSERT [dbo].[iller] ([id], [sehir]) VALUES (81, N'DÜZCE')
SET IDENTITY_INSERT [dbo].[iller] OFF