USE [master]
GO

/****** Object:  Database [SW]    Script Date: 14.09.2021 16:07:57 ******/
CREATE DATABASE [SW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CINARBILISIM\MSSQL\DATA\SW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CINARBILISIM\MSSQL\DATA\SW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SW] SET ARITHABORT OFF 
GO

ALTER DATABASE [SW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SW] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SW] SET RECOVERY FULL 
GO

ALTER DATABASE [SW] SET  MULTI_USER 
GO

ALTER DATABASE [SW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SW] SET  READ_WRITE 
GO

