CREATE DATABASE OTOMATIKISIMOLUSTUR



CREATE TABLE ISIMLER (AD VARCHAR (50), CINSIYET VARCHAR (1))


CREATE TABLE SOYISIMLER (SOYAD VARCHAR (50))
CREATE TABLE KISILER (AD VARCHAR (50),SOYISIM VARCHAR (50), DOGUMTARIHI DATE, YAS INT, YASGRUBU VARCHAR (30) )
CREATE TABLE EMAIL (EMAILDOMAIN VARCHAR (30))

CREATE TABLE STATE (STATE VARCHAR (30), CITY VARCHAR (30))

ALTER TABLE KISILER add COLUMN EPOSTA;

TRUNCATE TABLE KISILER


SELECT COUNT(*) FROM KISILER

