create trigger brute_force
ON ALL SERVER
AS 
BEGIN

DECLARE @COUNT AS INT
SELECT @COUNT =COUNT(*) FROM AUDIT.DBO.BRUTE_FORCE_ATTACK
WHERE COMPUTERIP=CONNECTIONPROPERTY ('client_net_address')


	IF ISNULL (@COUNT,0) > 0

	BEGIN 
		ROLLBACK
	END

END

-- BU ÝÞLEMLER YAPILIRKEN MASTER DATABASE YEDEÐÝNÝ ALDIKTAN SONRA YAPILMASI GEREKÝR.

-- kullanýcýlarýn ip lerini alýr.
SELECT CONNECTIONPROPERTY ('client_net_address')


SELECT @COUNT

-- SERVER OBJECTS ALTINDA TRÝGGER ALTINDA