INSERT INTO #LOG EXEC xp_readerrorlog

--create table #LOG (LOGDATE DATETIME, PROCESSINFO VARCHAR (100), TEXT VARCHAR (MAX))
SELECT * FROM #LOG WHERE TEXT LIKE'%FAÝLD%' and LOGDATE>= DATEADD(MINUTE, -3, GETDATE())
--TRUNCATE TABLE #log

DECLARE @IP AS VARCHAR (100)='192.168.1.1'
DECLARE @COUNT AS INT
DECLARE @BEGDATE AS DATETIME 
DECLARE @ENDDATE AS DATETIME
DECLARE @TEXT AS VARCHAR (1000) =''
DECLARE @MSG AS VARCHAR (1000) =''


SET @MSG ='SÝSTEMÝNÝZ SALDIRI ALTINDA'
SET @MSG = @MSG + @IP
SET @MSG = @MSG + 'DENENDÝ'+ CONVERT(VARCHAR, @COUNT) + 'YANLIÞ ÞÝFRE'
SET @MSG = @MSG + CONVERT (VARCHAR, @BEGDATE,108)+ ' AND'+CONVERT(VARCHAR,108)

SELECT @MSG


SELECT @COUNT=COUNT(*), @BEGDATE = MIN(LOGDATE), @ENDDATE=MAX(LOGDATE), @TEXT=TEXT
FROM #LOG 
WHERE  TEXT LIKE'%FAÝLD%' and LOGDATE>= DATEADD(MINUTE, -3, GETDATE())
GROUP BY TEXT HAVING COUNT(LOGDATE) > 100

SELECT @COUNT, @BEGDATE, @ENDDATE, @TEXT


SÝSTEMÝNÝZ SALDIRI ALTINDA. 192.168.1.1 ÝP DEN 551 DEFA SALDIRI YAPILDI
