-- RANDOM kisi tablosu oluþturma

DECLARE @I AS INT=0
WHILE @I < 10000
BEGIN



DECLARE @AD AS VARCHAR (50)
DECLARE @SOYAD VARCHAR (50)
DECLARE @DOGUMTARIHI DATE 
DECLARE @YAS AS INT
DECLARE @YASGRUBU AS VARCHAR (30)
DECLARE @EPOSTA AS VARCHAR (30)
DECLARE @EPOSTAT AS VARCHAR (30)
DECLARE @STATE AS VARCHAR(30)
DECLARE @CITY AS VARCHAR (30)
DECLARE @STREET AS VARCHAR (50)
DECLARE @ZIP AS INT	
DECLARE @PHONE AS INT


SELECT @AD=AD FROM ISIMLER WHERE ID =ROUND(RAND() * 1676,0)
SELECT @SOYAD=SOYISIM FROM SOYISIMLER WHERE ID =ROUND(RAND() * 1676,0)
SELECT @EPOSTA=EMAILDOMAIN FROM EMAIL WHERE ID =ROUND(RAND() * 9,0)
SELECT @STREET=STREET FROM STREET WHERE ID =ROUND(RAND() * 1000,0)
SELECT @CITY=CITY, @STATE=STATENAME FROM STATE WHERE ID =ROUND(RAND() * 50,0)

SET @ZIP= ROUND(RAND()*99999,0);
SET @DOGUMTARIHI= DATEADD (DAY, ROUND(RAND()*18250,0),'1950-01-01')
SET @YAS =DATEDIFF(YEAR, @DOGUMTARIHI,GETDATE())
SET @EPOSTAT = @AD+ @SOYAD+'@'+@EPOSTA
SET @PHONE = ROUND(RAND()*10000000,0);


IF @YAS BETWEEN 10 AND 20 
SET @YASGRUBU ='KUCUK'
	IF @YAS BETWEEN 21 AND 40 
SET @YASGRUBU ='ORTA YAS'
	IF @YAS BETWEEN 41 AND 60 
SET @YASGRUBU ='BUYUK'
	IF @YAS >60
SET @YASGRUBU ='YAÞLI'



INSERT INTO #KISILER (AD, SOYISIM, DOGUMTARIHI, YAS, YASGRUBU,EPOSTA, STATENAME, CITY, STREET, ZIP, PHONE) VALUES (@AD, @SOYAD, @DOGUMTARIHI, @YAS, @YASGRUBU, @EPOSTAT, @STATE, @CITY, @STREET,@ZIP, @PHONE)
SET @I=@I+1

END




create table #KISILER (AD varchar(30), SOYISIM varchar(30), DOGUMTARIHI date, YAS int, YASGRUBU varchar(30), EPOSTA varchar(30), 
STATENAME varchar(30), CITY varchar(30), STREET varchar(30), ZIP varchar(30), PHONE int)

alter table KISILER add id int identity(1,1)

SET STATISTICS TIME ON
SET STATISTICS IO ON 
--use tempdb
select  * from KISILER
--order by id desc
--where AD like '%ad%'
where AD='Jade' AND SOYISIM='Eanes' and 
eposta='JadeEanes@amazon.com'


select count (*) from KISILER
sp_spaceused KISILER

select 23802 *8 / 1024
select 4 *8 / 1024

create INDEX IX3 on  [dbo].[KISILER] ([id])
INCLUDE ([AD],[SOYISIM])

DROP INDEX [dbo].[KISILER].[PK_KISILER]




--kendi içinden kayýt ekler

insert into KISILER 
([AD], [SOYISIM], [DOGUMTARIHI], [YAS], [YASGRUBU], [EPOSTA], [STATENAME], [CITY], [STREET], [ZIP], [PHONE])

select top 1000 [AD], [SOYISIM], [DOGUMTARIHI], [YAS], [YASGRUBU], [EPOSTA], [STATENAME], [CITY], [STREET], [ZIP], [PHONE]
from KISILER