1) DAHA HIZLI
2) TOPLU ÝÞLEMLER RAM HIZINDA ÇALIÞIR
3) KOLAY GÜNCELLEME 
4) GÜVENLÝDÝR
5) YETKÝ KONTROLÜ YAPILABÝLÝR
6) YETENEKLÝDÝR
7) ESNEKTÝR. BÝRDEN FAZLA PROSEDÜRÜ ÝÇ ÝÇE KULLANABÝLÝRÝZ.
8) PERFORMANSI ÖLÇÜLEBÝLÝR. SÝSTEM KAYNAÐI KULLANIMI ÖLÇÜLEBÝLÝR.
