DECLARE @ITEMID AS INT
DECLARE @DATE AS DATETIME
DECLARE @AMOUNT AS INT
DECLARE @IOTYPE AS SMALLINT

SET ITEMID = ROUND(RAND() * 4,0)
IF @ITEMID =0
	SET @ITEMID =1
--SELECT ROUND(RAND() * 15,0)

SET @DATE = DATEADD(DAY, -ROUND(RAND() * 365 ,0), GETDATE())
--SELECT DATEADD(DAY, -ROUND(RAND() * 365 ,0), GETDATE())

SET @AMOUNT = ROUND(RAND()10,0)+1
SET @IOTYPE = ROUND(RAND()1,0)+1



INSERT INTO ITEMTRANSECTION
(ITEMID. DATE_, AMOUNT,IOTYPE)

SELECT @ITEMID AS ITEMID, @DATE AS DATE_, @AMOUNT AS AMOUNT, @IOTYPE AS IOTYPE 

VALUES()