--TRÝGGER

-- DATA MANÝPULASYONU 
-- ÝNSERT UPDATE DELETE BU KONUTLARDAN SONRA OTOMATÝK ÇALIÞMASI ÝÇÝN KULLANILIR.
-- OTOMATÝK HESAPLAMA, LOGLAMA, SON DEÐERÝ ALMA
-- SÜREKLÝ HAREKET OLAN TABLOLARDA HESAPLAMA ÝÞLEMLERÝ YAPILIR. STOK TABLOLARI EN ÝYÝ ÖRNEKTÝR.
-- OTOMATÝK TETÝKLEME ÝLE VERÝTABANINDA DEÐÝÞÝKLÝK OLDUÐUNDA ÇALIÞTIRILI.
-- TURNÝKE ÖRNEÐÝNDE KÝMLER ÝÇERDE KÝMLER DIÞARDA. PERSONEL TABLOSU ÇEKÝLÝR SON HAREKETLERÝ KONTROL EDÝLÝR.
-- TRÝGER ÝLE LOG LAMA YAPILIR. KÝMTARAFINDAN, NEZAMAN, HANGÝ BÝLGÝSAYARDAN, HANGÝ KULLANICI ÝLE, HANGÝ PROGRAM ÝLE, HANGÝ KOMUT CÜMLESÝ ÝLE YAPILDIÐI
-- 
