select * , 
case 
	when DATEPART(MONTH, order_date)= 1 THEN 'OCAK' 
	when DATEPART(MONTH, order_date)= 2 THEN 'ÞUBAT' 
	when DATEPART(MONTH, order_date)= 3 THEN 'MART' 
	when DATEPART(MONTH, order_date)= 4 THEN 'NÝSAN' 
	when DATEPART(MONTH, order_date)= 5 THEN 'MAYIS' 
	when DATEPART(MONTH, order_date)= 6 THEN 'HAZÝRAN' 
	when DATEPART(MONTH, order_date)= 7 THEN 'TEMMUZ' 
	when DATEPART(MONTH, order_date)= 8 THEN 'AÐUSTOS' 
	when DATEPART(MONTH, order_date)= 9 THEN 'EYLÜL' 
	when DATEPART(MONTH, order_date)= 10 THEN 'EKÝM'
	when DATEPART(MONTH, order_date)= 11 THEN 'KASIM' 
	when DATEPART(MONTH, order_date)= 12 THEN 'ARALIK' 
END

from sale.orders


CREATE FUNCTION DBO.GETMONTHNAME(@DATE AS DATETIME)
RETURNS VARCHAR (10)
AS 
BEGIN
DECLARE @AY AS VARCHAR(10)

	IF DATEPART(MONTH, @DATE)= 1 SET @AY ='01.OCAK' 
	IF DATEPART(MONTH, @DATE)= 2 SET @AY ='02.ÞUBAT' 
	IF DATEPART(MONTH, @DATE)= 3 SET @AY ='03.MART' 
	IF DATEPART(MONTH, @DATE)= 4 SET @AY ='04.NÝSAN' 
	IF DATEPART(MONTH, @DATE)= 5 SET @AY ='05.MAYIS' 
	IF DATEPART(MONTH, @DATE)= 6 SET @AY ='06.HAZÝRAN' 
	IF DATEPART(MONTH, @DATE)= 7 SET @AY ='07.TEMMUZ' 
	IF DATEPART(MONTH, @DATE)= 8 SET @AY ='08.AÐUSTOS' 
	IF DATEPART(MONTH, @DATE)= 9 SET @AY ='09.EYLÜL' 
	IF DATEPART(MONTH, @DATE)= 10 SET @AY ='10.EKÝM'
	IF DATEPART(MONTH, @DATE)= 11 SET @AY ='11.KASIM' 
	IF DATEPART(MONTH, @DATE)= 12 SET @AY ='12.ARALIK' 
RETURN @AY
END


SELECT DBO.GETMONTHNAME(GETDATE())