
select top 10000
COUNTRY_SHORT_NAME 
,PEOPLE_DEATH_NEW_COUNT as olum
,PEOPLE_POSITIVE_NEW_CASES_COUNT as pozitif
,REPORT_DATE1
,convert (decimal, PEOPLE_DEATH_NEW_COUNT) as olumDC
,convert(decimal, PEOPLE_POSITIVE_NEW_CASES_COUNT) as PozitifDC 
,(NULLIF(PEOPLE_DEATH_NEW_COUNT,0)/PEOPLE_POSITIVE_NEW_CASES_COUNT) 

from COVID
where PEOPLE_POSITIVE_NEW_CASES_COUNT <> 0

select NULLIF (0,0)
select ISNULL (0,1)

SELECT convert (decimal,ISNULL(PEOPLE_DEATH_NEW_COUNT/NULLIF(PEOPLE_POSITIVE_NEW_CASES_COUNT,0),0),2) AS oran FROM COVID