SELECT * FROM TEST

INSERT INTO TEST ([CUSTOMERNAME])
VALUES ('ÞUAYÝP555');

UPDATE WORKERTRANSACTIONS 
SET DATE_TARIH = CONVERT(DATE, DATE_) 


UPDATE WORKERTRANSACTIONS 
SET DATE_TARIH = NULL 




DELETE FROM TEST 
WHERE ID = 6

TRUNCATE TABLE TEST
SELECT * FROM TEST


SELECT top (100) *, CONVERT(DATE, DATE_) as date
from WORKERTRANSACTIONS;


select top (100) * from [dbo].[WORKERTRANSACTIONS]