SELECT        FINAL_CUSTOMER_RELATED_TABLE_FOR_DATATHON.BASE_CUSTOMER_ID, FINAL_CUSTOMER_RELATED_TABLE_FOR_DATATHON.VEHICLE_ID
FROM            FINAL_CUSTOMER_RELATED_TABLE_FOR_DATATHON INNER JOIN
                         FINAL_SIFIR_ARAC_ALANLAR_DATATHON ON FINAL_CUSTOMER_RELATED_TABLE_FOR_DATATHON.VEHICLE_ID = FINAL_SIFIR_ARAC_ALANLAR_DATATHON.VEHICLE_ID
WHERE        (FINAL_CUSTOMER_RELATED_TABLE_FOR_DATATHON.FK_RELATION_STATUS_EXPLANATION = N'Aktif Ruhsat Sahibi')