-- SORGU PARAMETRELERÝ TANIMLIYORUZ:

	-- PARAMETRELERE DEÐER ATAMAK ÝÇÝN SET VEYEA SELECT DÝYORUZ
DECLARE @P1 INT, @P2 INT, @SUM INT

SET @P1 = 6

SELECT @P2  =4

SELECT @SUM = @P1 + @P2

SELECT @SUM  -- SELECT ÝLE YAZDIRDIÐINDA SONUÇ RESULT KISMINDA ÇIKAR.

PRINT @SUM  -- PRINT ÝLE YAZDIRDIÐINDA SONUÇ MESSSAGE KISMINDA ÇIKAR.
-- DEÐER ATAMAK ÝÇÝN SET VEYA SELECT, 
-- PARAMETREYÝ ÇAÐIRMAK ÝÇÝN SELECT